// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoEPd3nw-9ASs-1FdXkEPKSUo89LXQ2X8',
    appId: '1:120009722321:web:7ca08d2ba9a67956d8b8f0',
    messagingSenderId: '120009722321',
    projectId: 'phoneauth-c41a0',
    authDomain: 'phoneauth-c41a0.firebaseapp.com',
    storageBucket: 'phoneauth-c41a0.appspot.com',
    measurementId: 'G-7668K25LLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm0-9IxF1OWsckKrhdUd0dZxz48UPPLCk',
    appId: '1:120009722321:android:aac575fae410b164d8b8f0',
    messagingSenderId: '120009722321',
    projectId: 'phoneauth-c41a0',
    storageBucket: 'phoneauth-c41a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-LCEmtQo7jgI6CVkoH3vC_ajMK3f9qo',
    appId: '1:120009722321:ios:ae61ac2959a5c1ead8b8f0',
    messagingSenderId: '120009722321',
    projectId: 'phoneauth-c41a0',
    storageBucket: 'phoneauth-c41a0.appspot.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI-LCEmtQo7jgI6CVkoH3vC_ajMK3f9qo',
    appId: '1:120009722321:ios:a2ebedb41c324a8ed8b8f0',
    messagingSenderId: '120009722321',
    projectId: 'phoneauth-c41a0',
    storageBucket: 'phoneauth-c41a0.appspot.com',
    iosBundleId: 'com.example.phoneAuth.RunnerTests',
  );
}
